spring.application.name=Hackathon1
github:
    token: ${GITHUB_TOKEN}

github.models.apiKey=TU_GITHUB_MODELS_PAT_OAUTH
github.models.available=\
openai/gpt-4,\
meta/llama-2-70b-chat,\
deepspeak/v1,\
multimodal/clip-vit-base

# PostgreSQL configuration

spring.datasource.url=jdbc:postgresql://localhost:5555/some-postgres
spring.datasource.username=postgre
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true